In [2]:
import torch
# Desired probabilities after applying sigmoid
probabilities = torch.tensor([0.95, 0.05, 0.05, 0.05])

# Calculate the logit (inverse of sigmoid) of these probabilities
# This will be the vector that gives the desired probabilities after applying sigmoid
logits = torch.log(probabilities / (1 - probabilities))

print("should be bad")
print(torch.sigmoid(probabilities))

print("model")
print(logits)

print("pass: should be [0.95, 0.05, 0.05, 0.05]")
print(torch.sigmoid(logits))

should be bad
tensor([0.7211, 0.5125, 0.5125, 0.5125])
model
tensor([ 2.9444, -2.9444, -2.9444, -2.9444])
pass: should be [0.95, 0.05, 0.05, 0.05]
tensor([0.9500, 0.0500, 0.0500, 0.0500])
